---
title: "Code for [Manuscript title]"
author: "Forrest Jones"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
library(cowplot)
library(tidybayes)
library(readxl)
library(survey)

expit = function(x) {1/(1+exp(-x))}

cumhaz_to_prob <- function(x) 1-exp(-x)



prevalence.est <- function(result, sens=0.90, spec=0.96, dsgn, d.f=NULL, alpha=0.05)
{
      result <- as.data.frame(result)
      n.row <- nrow(result)
      n.col <- ncol(result)
      pos.est <- result[, n.col-1]
      pos.se <- result[, n.col]
      prev.est <- (pos.est + spec - 1)/(sens + spec -1)
      prev.se <- (1/(sens + spec - 1)) * pos.se
      
      if(is.null(d.f)){
            for(i in 1:nrow(result)){
                  txt <- paste0("degf(subset(dsgn, ", names(result)[1], "=='", result[i, 1], "'")
                  if(n.col>3){
                        for(j in 2:(n.col-2)){
                              txt <- paste0(txt, " & ", names(result)[j], "=='", result[i, j], "'")
                        }
                  }
                  txt <- paste(txt, "))")
                  tmp.df <- eval(parse(text=txt))
                  d.f <- c(d.f, tmp.df)
            }
      }
      # calculating t value and confidence interval; t distribution has heavier tails than normal so it's better for confidence intervals of sample data
      t.val <- qt(1-alpha, df=d.f)
      lower <- pmax(prev.est-t.val*prev.se, 0)
      upper <- pmin(prev.est+t.val*prev.se, 1)
      
      result.mat <- cbind(point=prev.est, lower=lower, upper=upper)
      rownames(result.mat) <- rownames(result)
      result.mat
}






```


```{r load-files}

AS_Data_Probability <-  read_csv("data/raw_data/AS Data_Probability.csv") %>%
                        rename(`Record ID`=RecordID)

wide_dataset <- read_csv("data/generated_data/wide_dataset.csv")
long_dataset <- read_csv("data/generated_data/long_dataset.csv")
ArboNET_Case_Data <- read_excel("data/raw_data/ArboNET Case Data.xlsx")



neccesary_years= long_dataset %>%
                  group_by(`Record ID`)%>%
                        summarise(years_AS=sum(Former_location_group=="American Samoa"),
                                  loc_2017=Former_location_group[year==2017],
                                  loc_2018=Former_location_group[year==2018],
                                  n_years=n(),
                                  )


```


## Main  results

### Residency history of school children in 2023 serological survey 

```{r}


nrow(wide_dataset)

group_by(wide_dataset, birth_group) %>%
      summarise(
            n=n(),
            places=paste(unique(birthplace_clean),collapse=", ")
            ) %>%
      mutate(n/sum(n))

lifelongers<- long_dataset %>%
      group_by(`Record ID`)%>%
      filter(all(Former_location=="American Samoa") & all(Latter_location=="American Samoa")) %>%
      distinct(`Record ID`) 



      

nrow(lifelongers)
nrow(lifelongers)/nrow(wide_dataset)





nonendemies <- long_dataset %>%
            group_by(`Record ID`)%>%
            filter(sum(Former_location_group=="Non-endemic")>=2)%>%
            mutate(any_PI=any(Former_location_group=="Pacific Islands")) %>%
            filter(year %in% c(2017,2018)) %>%
            mutate(IN_AS=any(Former_location_group=="American Samoa")) %>%
            distinct(`Record ID`,IN_AS,any_PI) %>%
            ungroup()%>%
            left_join(wide_dataset) %>%
            mutate(`Final Test Result`=ifelse(`Final Test Result`=="P",
                                              "Positive","Negative"
                                              ))





nonendemies%>%
            group_by(IN_AS) %>%
            summarize(n=n(),
                      seropos=sum(`Final Test Result`=="Positive"),
                      seropos/n
                      )


long_dataset$Former_location_group %>% table()


long_dataset %>%
      filter(year %in% c(2017,2018)) %>%
      group_by(`Record ID`)%>%
      mutate(category=case_when(
            all(Former_location_group=="Pacific Islands") ~ "Pacific Islands",
            all(Former_location_group=="American Samoa") ~ "American Samoa",
            all(Former_location_group=="Non-endemic") ~ "Non-endemic",
            TRUE ~ "Mixed"
      )) %>% 
      distinct(`Record ID`,category) %>%
      left_join(wide_dataset) %>%
            group_by(category) %>%
            summarize(n=n(),
                      seropos=sum(`Final Test Result`=="P"),
                      seropos/n
                      )







```

## Table.

```{r}



wide_dataset %>%
      left_join(neccesary_years)%>%
      summarise(n=n(),age=median(`Calculated age based on DOB.`),
                lb_age = quantile(`Calculated age based on DOB.`,0.25),
              ub_age = quantile(`Calculated age based on DOB.`,0.75),
              female=sum(Sex=="Female"),
                            percent_female=mean(Sex=="Female"),
                          AS=median(years_AS/n_years),
                          lb_AS=quantile(years_AS/n_years,0.25),
                            ub_AS=quantile(years_AS/n_years,0.75),
                          seropos=sum(`Final Test Result`=="P"),
              ob=sum(loc_2017=="American Samoa" | loc_2018=="American Samoa"),
              ob_percent=mean(loc_2017=="American Samoa" | loc_2018=="American Samoa"),
            per_seropos=mean(`Final Test Result`=="P")
                )

wide_dataset %>%
      left_join(neccesary_years)%>%
      group_by(birth_group)%>%
      summarise(n=n(),age=median(`Calculated age based on DOB.`),
                lb_age = quantile(`Calculated age based on DOB.`,0.25),
              ub_age = quantile(`Calculated age based on DOB.`,0.75),
              female=sum(Sex=="Female"),
                            percent_female=mean(Sex=="Female"),
                          AS=median(years_AS/n_years),
                          lb_AS=quantile(years_AS/n_years,0.25),
                            ub_AS=quantile(years_AS/n_years,0.75),
                          seropos=sum(`Final Test Result`=="P"),
              ob=sum(loc_2017=="American Samoa" | loc_2018=="American Samoa"),
              ob_percent=mean(loc_2017=="American Samoa" | loc_2018=="American Samoa"),
            per_seropos=mean(`Final Test Result`=="P")
                )
      

# wide_dataset %>% 
#       count(School,birth_group) %>%
#       group_by(School)%>%
#       mutate(percent=n/sum(n))%>%
#       ggplot(aes(y=School,x=birth_group))+
#       geom_tile(aes(fill = percent))+
#       scale_fill_distiller(palette="Blues",direction = 1)
      


```

## Figure 1.

```{r}


silent_ob_2009 <- data.frame(
      serotype=c("DENV-4 outbreak?"),
      cases=55519*644/100000,
      year=c(2009)
      )

silent_ob_2015 <- data.frame(
      serotype=c("DENV-3 outbreak?"),
      cases=c(898/2),
      year=c(2015)
      )


f1 <- ArboNET_Case_Data %>%
      count(year) %>%
      bind_rows(data.frame(n=0,year=c(2019,2020,2021,2023))) %>%
      ggplot(aes(x=year,y=n))+
      geom_col(fill="#3182BD")+
      geom_col(data=silent_ob_2009,aes(x=year,y=cases),lty=2,fill=NA,
               col="black"
               )+
      geom_col(data=silent_ob_2015,aes(x=year,y=cases),lty=2,fill=NA,col="black")+
      geom_text(aes(label=n,y=n+15))+
      scale_x_continuous("Year",limits=c(2008,2024),breaks=2008:2023)+
      scale_y_continuous("Number of Cases", limits = c(0,600),breaks=seq(0,600,100))+
      theme_cowplot()+
      
      # Serosurvey annotation boxes
      annotate("label", x = 2010.5, y = 200,
               label = "2010 Serosurvey\n18–25 yrs: 89.0%\n26–40 yrs: 99.5%\nn=395",
               size = 4, color = "black", fill = "white", label.size = 0.5,
               lineheight = 1.3, hjust = 0.3, vjust = 0.5) +
      annotate("label", x = 2023, y = 200,
               label = "2023 Serosurvey\n7–16 yrs: 59%\nn=887",
               size = 4, color = "black", fill = "white", label.size = 0.5,
               lineheight = 1.2, hjust = 0.5, vjust = 0.5)+

      # Arrows from serosurvey boxes
      annotate("segment",
               x = 2011, xend = 2010.1,
               y = 120, yend = 0,
               arrow = arrow(length = unit(0.7, "cm")),
               color = "black", linewidth = 1.2) +
      annotate("segment",
               x = 2023, xend = 2023,
               y = 140, yend = 40,
               arrow = arrow(length = unit(0.7, "cm")),
               color = "black", linewidth = 1.2)+
      annotate("text", x = 2009, y = silent_ob_2009$cases+40,
               label = "DENV-4\noutbreak?",
               size = 4)+
      annotate("text", x = 2015, y = silent_ob_2015$cases+40,
               label = "DENV-3\noutbreak?",
               size = 4)+
      annotate("text", x = 2017, y = 508+60,
               label = "DENV-2\noutbreak",
               col="#3182BD",
               size = 4)



ggsave(filename="output/figures/figure1.png", plot=f1,height=3,width = 5.8,scale=1.5)
ggsave(filename="output/figures/figure1.pdf", plot=f1)
ggsave(filename="output/figures/figure1.tiff", plot=f1)




```



## Figure 2.

```{r}

survey_dataset <- wide_dataset %>%
      left_join(AS_Data_Probability)  %>%
      mutate(
            sero_binary = ifelse(`Final Test Result` == "P", 1, 0)
      ) %>%
      left_join(neccesary_years, by="Record ID") %>%
      mutate(ob_location=case_when(
            loc_2017 == "American Samoa" & loc_2018 == "American Samoa" ~ "American Samoa",
            loc_2017 == "Non-endemic" & loc_2018 == "Non-endemic" ~ "Non-endemic",
            loc_2017 == "Pacific Islands" & loc_2018 == "Pacific Islands" ~ "Pacific Islands",
            TRUE~ "Mixed"
      )) %>%
      mutate(birth_group=ifelse(str_detect(birth_group,"New Zealand"),
                             "Non-endemic",birth_group
                             ))

table(survey_dataset$ob_location)


# adding FPC (finite population correction) values based on original number of elem/hs schools sampled from
# 31 elementaries, 16 HS
survey_dataset$fpc <- ifelse(str_detect(survey_dataset$School,"Elementary"), 31, 16)
survey_dataset$SchoolLevel <- ifelse(str_detect(survey_dataset$School,"Elementary"), "Elementary", "High School")



as.dsn <- svydesign(
      id = ~School,
      strata=~SchoolLevel, probs=~prob,
      fpc=~fpc,
      data = survey_dataset
)

#overall prevalence estimate
tmp <- svymean(~sero_binary, design=as.dsn, na.rm=TRUE, method="likelihood", level=0.95)
overall_df <- prevalence.est(tmp, dsgn=as.dsn, d.f=degf(as.dsn), alpha=0.025) %>% 
      data.frame() %>%
      mutate(type="Overall")
overall_df$category <- "Overall"


# prevalence estimate by birth location
tmp2 <- svyby(
      ~sero_binary,
      by=~birth_group,        # <-- your stratifying variable
      design = as.dsn,
      FUN=svymean,
      na.rm = TRUE
)

# prevalence estimate by location during outbreak
birth_df<- prevalence.est(tmp2, dsgn=as.dsn,d.f=NULL, alpha=0.025)%>%
      data.frame()%>%
      mutate(type="Birth Location")
birth_df$category <- rownames(birth_df)

tmp3 <- svyby(
      ~sero_binary,
      ~ob_location,        # <-- your stratifying variable
      design = as.dsn,
      svymean,
      na.rm = TRUE
)




obloc_df <- prevalence.est(tmp3, dsgn=as.dsn, d.f=NULL,alpha=0.025)%>%
      data.frame()%>%
      mutate(type="OB Location")
obloc_df$category <- rownames(obloc_df)

f2_df <- bind_rows(overall_df,birth_df,obloc_df) %>%
      mutate(category=factor(category,
            levels = c("Overall",
            "American Samoa",
            "Pacific Islands",
            "Non-endemic",
            "Mixed"
            ),
            labels=c("Overall",
                     "American\nSamoa",
                     "Other tropical\nPacific Islands",
                     "Areas with\nlimited or no\ntransmission ",
                     "Multiple\nlocations"
                     )
            
      ))


survey_dataset %>%
      count(category=birth_group)%>%
      mutate(category=factor(category,
            levels = c("Overall",
            "American Samoa",
            "Pacific Islands",
            "Non-endemic",
            "Mixed"
            ),
            labels=c("Overall",
                     "American\nSamoa",
                     "Other tropical\nPacific Islands",
                     "Areas with\nlimited or no\ntransmission ",
                     "Multiple\nlocations"
                     )
            
      ))


f2a <- f2_df %>%
      filter(type %in% c("Overall","Birth Location")) %>%
      ggplot(aes(x=category))+
      geom_point(aes(y=point))+
      geom_linerange(aes(ymin=lower,ymax=upper))+
      scale_y_continuous("Dengue seroprevalence",limits=c(0,1))+
      xlab("Birth Location")+
      theme_cowplot()+
      theme(axis.text.x = element_text(angle = 45,hjust=1))

survey_dataset %>%
      count(category=ob_location,sero_binary)%>%
      mutate(category=factor(category,
            levels = c("Overall",
            "American Samoa",
            "Pacific Islands",
            "Non-endemic",
            "Mixed"
            ),
            labels=c("Overall",
                     "American\nSamoa",
                     "Other tropical\nPacific Islands",
                     "Areas with\nlimited or no\ntransmission ",
                     "Multiple\nlocations"
                     )
            
      ))


f2b <- f2_df %>%
      filter(type %in% c("Overall","OB Location")) %>%
      ggplot(aes(x=category))+
      geom_point(aes(y=point))+
      geom_linerange(aes(ymin=lower,ymax=upper))+
      scale_y_continuous("Dengue seroprevalence",limits=c(0,1))+
      xlab("Location during 2017-2018 outbreak")+
      theme_cowplot()+
      theme(axis.text.x = element_text(angle = 45,hjust=1))




f2 <- plot_grid(f2a,f2b,rel_widths = c(1,1.1),
                labels=c("A","B")
                )

f2      

ggsave(filename="output/figures/figure2.png", plot=f2, width=6.5,height=3.7,scale=1.5)
ggsave(filename="output/figures/figure2.pdf", plot=f2)
ggsave(filename="output/figures/figure2.tiff", plot=f2)


svyglm(sero_binary ~ birth_group, design = as.dsn, family = quasibinomial()) %>%
      summary()
svyglm(sero_binary ~ fct_rev(ob_location), design = as.dsn, family = quasibinomial()) %>% summary()


# #Dataset 2: Residency Figures 
# ### with weighted data####
# library(readxl)
# wgt_sum <- read_xlsx("wgt_sum.xlsx")### what is this file
# wgt_sum <- wgt_sum %>%
#       mutate(
#             point_prop = point / 100,
#             lower_prop = lower / 100,
#             upper_prop = upper / 100
#       )
# 
# f2a <- ggplot(wgt_sum, aes(x = birth_group, y = point_prop)) +
#       geom_point(size = 3, color = "blue") +  # Point estimates
#       geom_errorbar(aes(ymin = lower_prop, ymax = upper_prop), width = 0.2, color = "black") +  # Error bars for CIs
#       scale_y_continuous(limits = c(0, 1), 
#                          breaks = seq(0, 1, by = 0.2), 
#                          labels = scales::percent) +
#       labs(x = "Birthplace location group",
#            y = "Prevalence of previous dengue infection") +
#       theme_bw() +
#       theme(axis.text.x = element_text(angle = 0, hjust = 0.5))
# 
# f2a
# 
# ###weightedestimates###
# f2a <- survey_data1%>%
#       mutate(location_group = case_when(
#             birthplace_clean == "Missing" ~ NA_character_,  # Use NA_character_ for character columns
#             birthplace_clean == "American Samoa" ~ "American Samoa",
#             birthplace_clean %in% c("Western Samoa", "Fiji", "Tuvalu", "Philippines", "Hawaii") ~ "Pacific Islands",
#             birthplace_clean %in% c("New Zealand", "USA", "Australia") ~ "Non-endemic",
#             TRUE ~ birthplace_clean # Retain any other locations unchanged
#       ))%>%
#       group_by(location_group)%>%
#       summarise(seropos=mean(`Final Test Result`== "P")) %>%
#       ggplot(aes(x=location_group,y=seropos))+
#       geom_point()+
#       scale_y_continuous(limits=c(0,1))
# 
# 
# 
# ###weightedestimates###
# f2a <- survey_data1%>%
#       mutate(location_group = case_when(
#             birthplace_clean == "Missing" ~ NA_character_,  # Use NA_character_ for character columns
#             birthplace_clean == "American Samoa" ~ "American Samoa",
#             birthplace_clean %in% c("Western Samoa", "Fiji", "Tuvalu", "Philippines", "Hawaii") ~ "Pacific Islands",
#             birthplace_clean %in% c("New Zealand", "USA", "Australia") ~ "Non-endemic",
#             TRUE ~ birthplace_clean # Retain any other locations unchanged
#       ))%>%
#       group_by(location_group)%>%
#       summarise(seropos=mean(`Final Test Result`== "P")) %>%
#       ggplot(aes(x=location_group,y=seropos))+
#       geom_point()+
#       scale_y_continuous(limits=c(0,1))


```




## Figure 3

```{r}

#this step takes awhile
modelobject<- former <- read_rds(file="output/model_fits/20250818_188_former.rds")


f3 <- cowplot::plot_grid(
      former$p1 +cowplot::theme_cowplot()+scale_x_continuous(name='Birth year of serosurvey participant',breaks=9:17,labels=2015:2007),     
      cowplot::plot_grid(former$p2 +cowplot::theme_cowplot(),
                         former$p3 +cowplot::theme_cowplot(),nrow = 1,
                         labels=c("B","C")
      ), ncol=1,
      labels=c("A","")
      )


f3

ggsave(filename="output/figures/figure3.png", plot=f3, height=5)
ggsave(filename="output/figures/figure3.pdf", plot=f3)
ggsave(filename="output/figures/figure3.tiff", plot=f3)


```


## Figure 4

```{r eval=FALSE}

#Research Question 1: 1.Is there evidence of local transmission of dengue in American Samoa during years without cases reported?
# modelobject<- former <- read_rds(file="output/model_fits/20250603_2142_former.rds")

##modelfit<-read_rds("code/catalytic_model/as_denguefoi_fixeff_casess_Tlambda_17_mi_3_covs__ns_4_case2010to2022.rds")
modelfit<-modelobject$fit
# draws<-modelfit%>%
#       spread_draws(lambda[year])





#refining this based on the recs 
draws1 <- modelfit %>%
      spread_draws(lambda[year]) %>%
      group_by(year) %>%
      summarize(
            median = median(lambda * 4),
            lower = quantile(lambda * 4, 0.025),
            upper = quantile(lambda * 4, 0.975),
            .groups = 'drop'
      ) %>%
      mutate(actual_year = 2023 + (year - 64))%>%  # Convert index to actual years
      filter(actual_year >= 2008) 
      



f4a_p2_df



f4a_p2_df <- modelfit%>%
      gather_draws(logit_lambda_nonend,logit_lambda_end) %>%
      median_qi() %>%
      mutate(setting=ifelse(.variable=="logit_lambda_nonend",
                            "Non-endemic","Pacific Islands"
                            )) %>%
      mutate(.value=4*expit(.value),
             .lower  =4*expit(.lower),
             .upper =4*expit(.upper)
             ) %>%
      bind_rows(modelfit %>%
      spread_draws(lambda[year]) %>%
      mutate(actual_year = 2023 + (year - 64))%>%  # Convert index to actual years
      filter(actual_year >= 2008)   %>%
      group_by(.draw)%>%
      summarise(lambda=mean(lambda))%>%
      ungroup() %>%
      summarize(
            .value = median((lambda* 4) ),
            .lower = quantile((lambda* 4) , 0.025),
            .upper = quantile((lambda* 4) , 0.975),
            .groups = 'drop'
      ) %>%
      mutate(setting="American Samoa")
)

modelfit%>%
      gather_draws(logit_lambda_nonend,logit_lambda_end,lambda[year]) %>%
      mutate(actual_year = 2023 + (year - 64))%>%  # Convert index to actual years
      filter(actual_year >= 2008 |is.na(year))%>%
      group_by(.draw,.variable)%>%
      summarise(.value=mean(.value)) %>%
      mutate(.value=ifelse(.variable=="lambda",
                           cumhaz_to_prob(4*.value),
                           cumhaz_to_prob(4*expit(.value))))%>%
      group_by(.draw)%>%
      mutate(diff=.value[.variable=="lambda"]-.value)%>%
      group_by(.variable)%>%
      summarize(
            .lower = quantile(.value, 0.025),
            .upper = quantile(.value, 0.975),
            .value = median(.value),
            
            med_diff=median(diff),
            lb_diff=quantile(diff, 0.025),
            ub_diff=quantile(diff, 0.975),
            .groups = 'drop'
      ) %>%
      mutate(setting=factor(.variable,labels=c("American Samoa","Endemic","Non-endemic")) )
      
      

      # median_qi() %>%
      # mutate(setting=ifelse(.variable=="logit_lambda_nonend",
      #                       "Non-endemic","Pacific Islands"
      #                       )) %>%
      # mutate(.value=4*expit(.value),
      #        .lower  =4*expit(.lower),
      #        .upper =4*expit(.upper)
      #        )







lambdas <- former$fit %>% spread_draws(lambda[t]) 

ages <- 1:49
times <-1:64

cumlambdas <- data.frame()

for(i in times){
      for(a in ages){
            
            print(i)
            print(a)
            
            tmp_cum_lambdas <- lambdas %>% 
                  filter(t<=i) %>% ### only include the years that have occurred before or during time i
                  filter(t>=(i-a)) %>% ### only include those years where the individuals are alive
                  group_by(.draw)%>%
                  summarise(cumlambda=sum(lambda)) %>%
                  mutate(age=a,
                         year=i
                  )
            
            
            cumlambdas <- bind_rows(cumlambdas,
                                    tmp_cum_lambdas
            )
            
            
            
            
            
      }
}




# Convert cumulative FOI into population proportions
pop_groups<- cumlambdas %>%
      mutate(susc=exp(-4 * cumlambda),
             mono= 4*exp(-3*cumlambda)*(1-exp(-cumlambda)),
      )%>%
      mutate(the_rest=1-susc-mono)%>%
      group_by(.draw,year)%>%
      summarise(median=mean(cumlambda),
                susc=mean(susc),
                mono=mean(mono),
                the_rest=mean(the_rest)
      ) 



# Line plot with ribbon

#this is for year 2023 
draws3_2023 <- modelfit %>%
      spread_draws(mono[age, year]) %>%
      filter(year == 8) %>%
      group_by(age) %>%
      summarise(
            median = median(mono),
            lb = quantile(mono, 0.025),
            ub = quantile(mono, 0.975),
            .groups = 'drop'
      )

```


```{r eval=FALSE}

# write_rds(draws1,"data/generated_data/figure4/draws1.rds")
# write_rds(f4a_p2_df,"data/generated_data/figure4/f4a_p2_df.rds")
# write_rds(pop_groups,"data/generated_data/figure4/pop_groups.rds")
# write_rds(cumlambdas,"data/generated_data/figure4/cumlambdas.rds")
# write_rds(draws3_2023,"data/generated_data/figure4/draws3_2023.rds")

```


```{r}


draws1 <- read_rds("data/generated_data/figure4/draws1.rds")
f4a_p2_df <- read_rds("data/generated_data/figure4/f4a_p2_df.rds")
pop_groups <- read_rds("data/generated_data/figure4/pop_groups.rds")
cumlambdas <- read_rds("data/generated_data/figure4/cumlambdas.rds")
draws3_2023 <- read_rds("data/generated_data/figure4/draws3_2023.rds")





#regular FOI
draws1

#discrete hazard
draws1 %>%
      mutate(across(median:upper, .fns= ~ cumhaz_to_prob(.x)))
      
f4a_p2_df%>%
      mutate(across(.value:.upper, .fns= ~ cumhaz_to_prob(.x)))

f4b_table %>%
      filter(year==2016)

f4b_table %>%
      filter(Type=="DENV-naïve")

f4b_table %>%
      filter(Type=="Primary")


draws3_2023 %>% filter(median==max(median))



modelfit %>%
      spread_draws(lambda[year])%>%
      mutate(actual_year = 2023 + (year - 64))%>%  # Convert index to actual years
      filter(actual_year %in% c())  %>%
      group_by(year) %>%
      summarize(
            median = median(lambda * 4),
            lower = quantile(lambda * 4, 0.25),
            upper = quantile(lambda * 4, 0.75),
            .groups = 'drop'
      )


pop_groups%>%
      mutate(actual_year = 2023 + (year - 64)) %>%
      filter(actual_year %in% c(2016,2018,2023)) %>% 
      group_by(.draw) %>%
      mutate(diff_2016=susc-susc[actual_year==2016],
             ratio_2016=susc/susc[actual_year==2016]
             )%>%
      group_by(actual_year) %>%
      summarise(median(ratio_2016),
                quantile(ratio_2016,0.025),
              quantile(ratio_2016,0.975)
                )

```


```{r}



f4a_p1 <- ggplot(draws1, aes(x = actual_year)) +
      geom_point(aes(y = cumhaz_to_prob(median))) +
      geom_linerange(aes(ymin = cumhaz_to_prob(lower), ymax = cumhaz_to_prob(upper))) +
      scale_x_continuous("Year",breaks = 2008:2023) +  # Show all years
      theme_minimal() +  # Using minimal theme
      theme(
            panel.grid.minor = element_blank(),  # Remove minor grid lines
            panel.grid.major = element_blank(),  # Remove major grid lines
            panel.background = element_blank(),   # Remove panel background
            plot.background = element_blank(),    # Remove plot background
            axis.line = element_line(color = "black")  # Add axis lines
      )+ 
      theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) +
                scale_y_continuous("Force of Infection",
                                   limits=c(0,0.7)
                                   )

f4a_p2<- f4a_p2_df%>%
      # mutate(setting=ifelse(setting=="Non-endemic",
      #                          "Areas with\nlimited or no\ntransmission ",
      #                        "Other Tropical\nIslands"
      #                       ))%>%
      ggplot(aes(x=(setting),y=cumhaz_to_prob(.value)))+
      geom_point()+
      geom_linerange(aes(ymin=cumhaz_to_prob(.lower),ymax=cumhaz_to_prob(.upper)))+
      theme_minimal()+
      xlab("Setting") +  # Using minimal theme
      theme(
            panel.grid.minor = element_blank(),  # Remove minor grid lines
            panel.grid.major = element_blank(),  # Remove major grid lines
            panel.background = element_blank(),   # Remove panel background
            plot.background = element_blank(),    # Remove plot background
            axis.line = element_line(color = "black")  # Add axis lines
      )+ 
      theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) +
                scale_y_continuous("Force of Infection",
                                   limits=c(0,0.6)
                                   )


f4b_data <- pop_groups %>%
      select(-median) %>%
      gather(type, value, -c(year, .draw)) %>%
      group_by(type, year) %>%
      summarise(
            median = (median(value)),
            lb = (quantile(value, 0.025)),
            ub = (quantile(value, 0.975)),
            .groups = "drop"
      )

# Fix and relabel data for plot
f4b_table <- f4b_data %>%
      mutate(
            year = 2023 - 64 + year,
            Type = factor(type, levels = c("susc", "mono", "the_rest"),
                          labels = c("DENV-naïve", "Primary", "Multiple"))
      ) %>%
      filter(year >= 2008) %>%
      select(year, Type, median, lb, ub) %>%
      arrange(year, Type)


library(scales)

f4b <- ggplot(f4b_table, aes(x = year, y = median, color = fct_rev(Type), fill = fct_rev(Type))) +
      geom_line(linewidth = 1) +
      geom_ribbon(aes(ymin = lb, ymax = ub), alpha = 0.4, color = NA) +
      
      # Add year breaks on x-axis
      scale_x_continuous(
            breaks = seq(min(f4b_table$year), max(f4b_table$year), by = 1)
      ) +
      
      # Format y-axis as percentages
      scale_y_continuous(labels = percent_format(accuracy = 1)) +
      
      labs(
            x = "Year",
            y = "Proportion of Population",
            color = "Infection History",
            fill = "Infection History"
      ) +
       scale_color_brewer(palette = "Dark2")+
      scale_fill_brewer(palette = "Dark2")+
      theme_minimal(base_size = 12) +
      theme(
            legend.title = element_text(face = "bold"),
            legend.text = element_text(size = 10),
            axis.text = element_text(size = 10),
            axis.title = element_text(size = 10),
            panel.grid.minor = element_blank(),
            panel.grid.major = element_blank(),
            panel.background = element_blank(),
            plot.background = element_blank(),
            axis.line = element_line(color = "black"),
            axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1) 
            
      )

f4c <- ggplot(draws3_2023, aes(x = age, y = median)) +
      geom_line() +
      geom_ribbon(alpha = 0.5, aes(ymin = lb, ymax = ub)) +
      labs(x = "Age (years) in 2023",
           y = "Proportion of population\nwith one previous DENV infection") +
      scale_y_continuous(labels = scales::percent_format(), limits = c(0, 0.5)) + 
      scale_x_continuous(limits = c(0, 50), breaks = seq(0, 50, 5)) +  # Set limits and breaks
      theme_minimal() +
      theme(
            panel.grid.minor = element_blank(),  # Remove minor grid lines
            panel.grid.major = element_blank(),  # Remove major grid lines
            panel.background = element_blank(),   # Remove panel background
            plot.background = element_blank(),    # Remove plot background
            axis.line = element_line(color = "black")  # Add axis lines
      )


modelobject$fit%>%
      spread_draws(mono[age, year]) %>%
      filter(year %in% c(1,3,8)) %>%
      group_by(age,year) %>%
      summarise(
            median = median(mono),
            lb = quantile(mono, 0.025),
            ub = quantile(mono, 0.975),
            .groups = 'drop'
      ) %>%
      ggplot(aes(x=age,y=median,col=factor(year+2015),fill = factor(year+2015)))+
      # geom_ribbon(aes(ymin=lb,ymax=ub),alpha=0.5,col=NA)+
      geom_line()

figure4 <- plot_grid(f4a_p1,f4a_p2,
          f4b+theme(legend.position = "none"),
                get_legend(f4b),
                  f4c,
      ggplot()+theme_void(),
      nrow=3,
      align = "hv",
      axis="bl",
       label_size = 12,   
       labels = c("A","B","C","","D",""),
      rel_widths = c(3,1.5)

)
          
          
      

figure4

ggsave(filename = "output/figures/figure4.png",
       plot = figure4,
       height = 6.42,
       width = 4.34,
       scale=1.5
       )

ggsave(filename = "output/figures/figure4.pdf",
       plot = figure4,
       height = 6.42,
       width = 4.34,
       scale=1.5
       )

ggsave(filename = "output/figures/figure4.tiff",
       plot = figure4,
       height = 6.42,
       width = 4.34,
       scale=1.5
       )


```




### supplementary figures

### Cohort figure


```{r}


cohort_df <- long_dataset %>%
      filter(birthplace_clean %in% c("Australia","New Zealand","USA","Hawaii")) %>%
      mutate(pretty_former=ifelse(Former_location_group=="Non-endemic",
                                  "Areas with limited\nor no transmission",
                                  Former_location_group
                                  ))%>%
      left_join(distinct(wide_dataset,`Final Test Result`,`Record ID`)) %>%
      mutate(test_result=ifelse(`Final Test Result`=="P","Positive","Negative"))


cohort_fig <- cohort_df%>%
      ggplot(aes(x=factor(year),y=reorder(factor(`Record ID`),yob)))+
      geom_tile(aes(fill = pretty_former),col=NA)+
      geom_tile(data=cohort_df %>%
            filter(year %in% c(2017,2018)),fill=NA,col="black")+
      facet_grid(test_result~., scales="free_y", space = "free_y")+
      ylab("Serosurvey Participant ID")+
      xlab("Year")+
      scale_fill_brewer("Location", palette="Set2")+
      theme_cowplot()+
      theme(axis.text.y = element_blank(),
            axis.ticks.y = element_blank(),
            axis.text.x = element_text(angle=45,hjust = 1))

cohort_fig

ggsave(plot=cohort_fig,filename = "output/figures/supplementary_figures/cohort.png")
ggsave(plot=cohort_fig,filename = "output/figures/supplementary_figures/cohort.pdf")
ggsave(plot=cohort_fig,filename = "output/figures/supplementary_figures/cohort.tiff")

# plot_grid(fig2c,labels=c("C"))

# library(cowplot)
# 
# fig_df_2b <-long_dataset %>%
#       inner_join(distinct(nonendemies,`Record ID`,`Final Test Result`,birth_group,IN_AS)) %>%
#       filter(IN_AS)
# 
# f2b <- fig_df_2b%>%
#       ggplot(aes(x=factor(year), y=reorder(factor(`Record ID`),yob)))+
#       geom_tile(aes(fill=Former_location_group))+
#       geom_tile(data=fig_df_2b %>%
#             filter(year %in% c(2017,2018)),fill=NA,col="black")+
# 
#       # geom_vline(
#       #       xintercept = which(levels(factor(f2b$year)) == "2017"),
#       #       color = "black",
#       #       linewidth = 3  
#       # )+
#       facet_grid(`Final Test Result`~., scales="free_y", space = "free_y")+
#       ylab("Serosurvey Participant ID")+
#       scale_x_discrete("Year",limits=factor(2007:2023))+
#       scale_fill_brewer("Location", palette="Set2")+
#       theme_cowplot()+
#       theme(axis.text.y = element_blank(),
#             axis.ticks.y = element_blank(),
#             axis.text.x = element_text(angle=45,hjust = 1))+
#       ggtitle("Resided in American Samoa\nduring outbreak")
# 
# 
# fig_df_2c <-long_dataset %>%
#       inner_join(distinct(nonendemies,`Record ID`,`Final Test Result`,birth_group,IN_AS)) %>%
#       filter(!IN_AS)
#       
# 
# 
# f2c <- fig_df_2c%>%
#       ggplot(aes(x=factor(year), y=reorder(factor(`Record ID`),yob)))+
#       geom_tile(aes(fill=Former_location_group))+
#       geom_tile(data=fig_df_2c %>%
#             filter(year %in% c(2017,2018)),fill=NA,col="black")+
# 
#       # geom_vline(
#       #       xintercept = which(levels(factor(f2b$year)) == "2017"),
#       #       color = "black",
#       #       linewidth = 3  
#       # )+
#       facet_grid(`Final Test Result`~., scales="free_y", space = "free_y")+
#       ylab("Serosurvey Participant ID")+
#       xlab("Year")+
#       scale_fill_brewer("Location", palette="Set2")+
#       theme_cowplot()+
#       theme(axis.text.y = element_blank(),
#             axis.ticks.y = element_blank(),
#             axis.text.x = element_text(angle=45,hjust = 1))+
#       ggtitle("Did not reside in\nAmerican Samoa during outbreak")
# 
# 
# 
# plot_grid(f2b+theme(legend.position = "none")
#                 ,f2c,
#           rel_widths = c(1,1.35)
#           )

# 
# long_dataset %>%
#       inner_join(distinct(nonendemies,`Record ID`,`Final Test Result`,birth_group)) %>%
#       filter(birth_group=="American Samoa")%>%
#       ggplot(aes(x=factor(year), y=reorder(factor(`Record ID`),yob)))+
#       geom_tile(aes(fill=Former_location_group),col="black")+
#       # geom_vline(
#       #       xintercept = which(levels(factor(f2b$year)) == "2017"),
#       #       color = "black",
#       #       linewidth = 3  
#       # )+
#       facet_grid(`Final Test Result`~birth_group, scales="free_y", space = "free_y")+
#       ylab("Serosurvey Participant ID")+
#       xlab("Year")+
#       scale_fill_brewer("Location", palette="Set2")+
#       theme_cowplot()+
#       theme(axis.text.y = element_blank(),
#             axis.ticks.y = element_blank(),
#             axis.text.x = element_text(angle=45,hjust = 1)
#       )
# 
# 
# long_dataset %>%
#       inner_join(distinct(nonendemies,`Record ID`,`Final Test Result`,birth_group)) %>%
#       filter(birth_group!="American Samoa")%>%
#       ggplot(aes(x=factor(year), y=reorder(factor(`Record ID`),yob)))+
#       geom_tile(aes(fill=Former_location_group),col="black")+
#       # geom_vline(
#       #       xintercept = which(levels(factor(f2b$year)) == "2017"),
#       #       color = "black",
#       #       linewidth = 3  
#       # )+
#       facet_grid(`Final Test Result`~birth_group, scales="free_y", space = "free_y")+
#       ylab("Serosurvey Participant ID")+
#       xlab("Year")+
#       scale_fill_brewer("Location", palette="Set2")+
#       theme_cowplot()+
#       theme(axis.text.y = element_blank(),
#             axis.ticks.y = element_blank(),
#             axis.text.x = element_text(angle=45,hjust = 1)
#       )
# 
# 
# long_dataset %>%
#       inner_join(distinct(nonendemies,`Record ID`,`Final Test Result`,birth_group,IN_AS)) %>%
#       filter(`Final Test Result`=="P")%>% 
#       ggplot(aes(x=factor(year), y=reorder(factor(`Record ID`),yob)))+
#       geom_tile(aes(fill=Former_location_group))+
#       geom_tile(data=long_dataset %>%
#       inner_join(distinct(nonendemies,`Record ID`,`Final Test Result`,birth_group,IN_AS)) %>%
#       filter(`Final Test Result`=="P") %>%
#             filter(year %in% c(2017,2018)),fill=NA,col="black")+
# 
#       # geom_vline(
#       #       xintercept = which(levels(factor(f2b$year)) == "2017"),
#       #       color = "black",
#       #       linewidth = 3  
#       # )+
#       facet_grid(IN_AS~`Final Test Result`, scales="free_y", space = "free_y")+
#       ylab("Serosurvey Participant ID")+
#       xlab("Year")+
#       scale_fill_brewer("Location", palette="Set2")+
#       theme_cowplot()+
#       theme(axis.text.y = element_blank(),
#             axis.ticks.y = element_blank(),
#             axis.text.x = element_text(angle=45,hjust = 1))
# 
# long_dataset %>%
#       inner_join(distinct(nonendemies,`Record ID`,`Final Test Result`,birth_group,IN_AS)) %>%
#       filter(`Final Test Result`=="N")%>%
#       ggplot(aes(x=factor(year), y=reorder(factor(`Record ID`),yob)))+
#       geom_tile(aes(fill=Former_location_group))+
#       geom_tile(data=long_dataset %>%
#       inner_join(distinct(nonendemies,`Record ID`,`Final Test Result`,birth_group,IN_AS)) %>%
#       filter(`Final Test Result`=="N") %>%
#             filter(year %in% c(2017,2018)),fill=NA,col="black")+
# 
#       # geom_vline(
#       #       xintercept = which(levels(factor(f2b$year)) == "2017"),
#       #       color = "black",
#       #       linewidth = 3  
#       # )+
#       facet_grid(IN_AS~`Final Test Result`, scales="free_y", space = "free_y")+
#       ylab("Serosurvey Participant ID")+
#       xlab("Year")+
#       scale_fill_brewer("Location", palette="Set2")+
#       theme_cowplot()+
#       theme(axis.text.y = element_blank(),
#             axis.ticks.y = element_blank(),
#             axis.text.x = element_text(angle=45,hjust = 1))




```


### Location dataset sensitivity analyses


```{r}

all_draws <- read_rds("data/generated_data/supplement/all_draws.rds")



all_draws %>%
      mutate(year=2023-max(year)+year) %>%
      group_by(year,population)%>%
      median_qi() %>%
      filter(year>=2008)%>%
      mutate(Population=case_when(
            population=="everyone" ~ "All participants,\nno residency data",
            population=="lifelong" ~ "Only lifelong residents,\nno residency data",
            population=="latter" ~ "All participants,\nlatter location used",
            population=="former" ~ "All participants,\nformer location used"
      ))%>%
      ggplot(aes(x=factor(year),y=cumhaz_to_prob(lambda*4),col=Population))+
      geom_point(aes(col=Population),
                 position = position_dodge(0.5)
                 )+
      geom_linerange(aes(col=Population,
                         ymin=cumhaz_to_prob(.lower*4),ymax = cumhaz_to_prob(.upper*4)),
                     position = position_dodge(0.5)
                     )+
      scale_color_viridis_d()+
      xlab("Year")+
      ylab("Force of Infection")+
      theme_cowplot()

```


### Combo fit figure 1

```{r}



read_rds(file="output/model_fits/20250818_1943_former_combo1718.rds")%>% 
      spread_draws(lambda[year]) %>%
      ungroup()%>%
      mutate(year=2023-max(year)+year) %>%
      mutate(newyear=case_when(
            year>2018 ~ as.character(year),
            year==2018 ~"2017-2018",
            year<2018 ~ as.character(year-1)
      )) %>%
      filter(year>=2009)%>%
      group_by(newyear)%>%
      median_qi() %>%
      ggplot(aes(x=newyear,y=cumhaz_to_prob(lambda*4)))+
      geom_point()+
      geom_linerange(aes(ymin=cumhaz_to_prob(lambda.lower*4),ymax =cumhaz_to_prob( lambda.upper*4)))+
      scale_y_continuous(limits=c(0,0.75))+
      xlab("Year")+ylab("Force of Infection")+
      theme_cowplot()+
      theme(axis.text.x = element_text(angle = 45,hjust=1))

read_rds(file="output/model_fits/20250818_1943_former_combo1718.rds")%>% 
      gather_draws(logit_lambda_nonend,logit_lambda_end) %>%
      median_qi() %>%
      mutate(setting=ifelse(.variable=="logit_lambda_nonend",
                            "Non-endemic","Pacific Islands"
                            )) %>%
      mutate(.value=4*expit(.value),
             .lower  =4*expit(.lower),
             .upper =4*expit(.upper)
             )




```

### Combo fit figure 2

```{r}


read_rds("data/generated_data/supplement/pop_groups_supplement.rds") %>%
      select(-median) %>%
      gather(type,value,-c(year,.draw)) %>%
      group_by(type,year)%>%
      summarise(median=median(value),
                lb=quantile(value,0.025),
                ub=quantile(value,0.975)
      ) %>%
      mutate(Type=factor(type,levels=c("susc", "mono", "the_rest"),labels=c("DENV-naïve","Primary", "Multiple")))%>%
      mutate(year=2023-max(year)+year) %>%
      mutate(newyear=case_when(
            year>2018 ~ as.character(year),
            year==2018 ~"2017-2018",
            year<2018 ~ as.character(year-1)
      )) %>%
      filter(year>=2009)%>%
      ggplot(aes(x=newyear,col=fct_rev(Type),fill=fct_rev(Type),group=fct_rev(Type)))+
      geom_line(aes(y=median))+
      geom_ribbon(aes(ymin=lb,ymax=ub),alpha=0.5,col=NA)+
      scale_color_brewer(palette = "Dark2")+
      scale_fill_brewer(palette = "Dark2")+
      labs(
            #title = "Trends in Population Immunity Over Time",
            x = "Year",
            y = "Proportion of population by DENV infection History",
            color = "Infection History",
            fill = "Infection History"
      ) +
      theme_minimal()+
      theme(axis.text.x = element_text(angle = 45,hjust=1))



#this is for year 2023 
read_rds(file="output/model_fits/20250818_1943_former_combo1718.rds")%>% 
      spread_draws(mono[age, year]) %>%
      filter(year %in% c(1,2,7)) %>%
      group_by(age,year) %>%
      summarise(
            median = median(mono),
            lb = quantile(mono, 0.025),
            ub = quantile(mono, 0.975),
            .groups = 'drop'
      ) %>%
      ggplot(aes(x=age,y=median,col=factor(year+2015),fill = factor(year+2015)))+
      geom_ribbon(aes(ymin=lb,ymax=ub),alpha=0.5,col=NA)+
      geom_line()

```


#### Table 2. Relative risk estimate


```{r}

modelobject<- read_rds(file="output/model_fits/20250818_188_former.rds")



med_ci <- function(param) {
      
      med <-round(median(param),2)
      lb  <- round(quantile(param,0.025),2)
      ub  <- round(quantile(param,0.975),2)

      glue::glue("{med} ({lb}–{ub})")
}
  

difference_df <- modelobject$fit %>%
      spread_draws(lambda[year],logit_lambda_end,logit_lambda_nonend)%>%
      mutate(actual_year = 2023 + (year - 64)) %>%
      filter(actual_year >= 2008)%>%
      mutate(
             lambda=cumhaz_to_prob(4*lambda),
             lambda_end=cumhaz_to_prob(4*expit(logit_lambda_end)),
             lambda_nonend=cumhaz_to_prob(4*expit(logit_lambda_nonend))
             )%>%
      mutate(endemic_diff=lambda-lambda_end,
             nonendemic_diff=lambda-lambda_nonend
             ) %>%
      group_by(actual_year) %>% 
      summarise(
            AS_FOI=med_ci(lambda),
            END_FOI=med_ci(lambda_end),
            END_DIFF=med_ci(endemic_diff),
            NONEND_FOI=med_ci(lambda_nonend),
            NONEND_DIFF=med_ci(nonendemic_diff),
      ) 


difference_df%>%
      mutate(actual_year=as.character(actual_year))%>%
      rename(
            Year=actual_year,
            `American Samoa`=AS_FOI,
            `Other Tropical Islands`=END_FOI,
            `Areas with limited nor no transmission`=NONEND_FOI
      ) %>%
      flextable::flextable() %>%
      flextable::autofit() %>%
      flextable::save_as_docx(path="output/figures/supplementary_figures/difftable.docx")



```




